###!
# Start Bootstrap - Stylish Portfolio (http://startbootstrap.com/)
# Copyright 2013-2017 Start Bootstrap
# Licensed under MIT (https://github.com/BlackrockDigital/startbootstrap/blob/gh-pages/LICENSE)
###

(($) ->
  'use strict'
  # Start of use strict
  # Closes the sidebar menu
  $('#menu-close').click (e) ->
    e.preventDefault()
    $('#sidebar-wrapper').toggleClass 'active'
    return
  # Opens the sidebar menu
  $('#menu-toggle').click (e) ->
    e.preventDefault()
    $('#sidebar-wrapper').toggleClass 'active'
    return
  # Smooth scrolling using jQuery easing
  $('a.js-scroll-trigger[href*="#"]:not([href="#"])').click ->
    if location.pathname.replace(/^\//, '') == @pathname.replace(/^\//, '') and location.hostname == @hostname
      target = $(@hash)
      target = if target.length then target else $('[name=' + @hash.slice(1) + ']')
      if target.length
        $('html, body').animate { scrollTop: target.offset().top }, 1000, 'easeInOutExpo'
        return false
    return
  # Closes responsive menu when a scroll trigger link is clicked
  $('.js-scroll-trigger').click ->
    $('#sidebar-wrapper').removeClass 'active'
    return
  ##to-top button appears after scrolling
  fixed = false
  $(document).scroll ->
    if $(this).scrollTop() > 250
      if !fixed
        fixed = true
        $('#to-top').show 'slow', ->
          $('#to-top').css
            position: 'fixed'
            display: 'block'
          return
    else
      if fixed
        fixed = false
        $('#to-top').hide 'slow', ->
          $('#to-top').css display: 'none'
          return
    return
  return
) jQuery
# End of use strict
# Disable Google Maps scrolling
# See http://stackoverflow.com/a/25904582/1607849
# Disable scroll zooming and bind back the click event

onMapMouseleaveHandler = (event) ->
  that = $(this)
  that.on 'click', onMapClickHandler
  that.off 'mouseleave', onMapMouseleaveHandler
  that.find('iframe').css 'pointer-events', 'none'
  return

onMapClickHandler = (event) ->
  that = $(this)
  # Disable the click handler until the user leaves the map area
  that.off 'click', onMapClickHandler
  # Enable scrolling zoom
  that.find('iframe').css 'pointer-events', 'auto'
  # Handle the mouse leave event
  that.on 'mouseleave', onMapMouseleaveHandler
  return

# Enable map zooming with mouse scroll when the user clicks the map
$('.map').on 'click', onMapClickHandler

# ---
# generated by js2coffee 2.2.0
